### ISSUE TITLE
Allow setting worker threads on zstd to automatic

### ISSUE THREAD

**Issue by viceice** [jenkinsci/jobcacher-plugin#107]
### What feature do you want to see added?

I like to set the zstd worker threads to `0` (automatic, uses number oth cores)

https://github.com/luben/zstd-jni/blob/bb156dcb84c79b76b3178046f4df64213dd881e8/src/main/java/com/github/luben/zstd/ZstdOutputStream.java#L136

Sadly it's not possible via commons.compress

https://github.com/apache/commons-compress/blob/d2841ff43cbc401378231820e71018c1cbb0c240/src/main/java/org/apache/commons/compress/compressors/zstandard/ZstdCompressorOutputStream.java#L34

it's probably a good idea to set it to `0` by default to support faster compression on multithreaded systems

- #91

**Comment by repolevedavaj** [comment]
@viceice see #113. I am curious if you see a significant performance improvement by using this.

**Comment by viceice** [comment]
I'll test it out after the wildcard feature. already installed the version but hadn't time to test yet.

**Comment by repolevedavaj** [comment]
> I'll test it out after the wildcard feature. already installed the version but hadn't time to test yet.

No hurry ;)

**Comment by repolevedavaj** [comment]
If its easier for you, i can merge all PRs so you can try it out in a official release. If there is any change needed, i can modify it again in a second round. What do you think?

**Comment by viceice** [comment]
sounds good 🤗 hopefully we don't break existing users 🙃
