### ISSUE TITLE
Option to always restore cache

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/jobcacher-plugin#117]
### What feature do you want to see added?

Hi,

I would like to use jobCacher to cache the sonar scanner downloaded jars.

In order to avoid updating the cache on each execution, I want to use the `cacheValidityDecidingFile`. But I'm not sure what to use in case of SonarQube

My idea was to use a Glob Ant pattern to check the if the downloaded jar are the same like `**/.sonar/cache/**/sonar-*-plugin.jar` (cache would be in the workspace)

But the side effect of this is that the cache is never restored because those files doesn't exists (they exists only when the SonarQube scanner runs)

An option would be a flag to always restore the cache and keep the same behavior for updating the cache based on the `cacheValidityDecidingFile`

Now we have

**1st execution** 
```
[Cache for /home/jenkins/agent/workspace/*****/.sonar/cache] Skip restoring cache as no up-to-date cache exists
[Cache for /home/jenkins/agent/workspace/*****/.sonar/cache] Creating cache...
```

**2nd execution**  (cache is not restored probably cacheValidityDecidingFile is not computed across files
```
[Cache for /home/jenkins/agent/workspace/*****/.sonar/cache] Skip restoring cache as no up-to-date cache exists
[Cache for /home/jenkins/agent/workspace/****/.sonar/cache] Skip cache creation as the cache is up-to-date
```

Any idea how to fix this ?

Best regards,

Valentin

**Comment by repolevedavaj** [comment]
I think the idea of restoring the cache if the `cacheValidityDecidingFile` does not exist sounds good to me

**Comment by jonesbusy** [comment]
> I think the idea of restoring the cache if the `cacheValidityDecidingFile` does not exist sounds good to me

Looks also a good approach to me
