### ISSUE TITLE
Job cacher not working as expected

### ISSUE THREAD

**Issue by ariretiarno** [jenkinsci/jobcacher-plugin#124]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins version: 2.319.1
Docker
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins version: 2.319.1
Docker
SIngle Node
Agent on master

### Reproduction steps

Without job cacher plugin
1. Create Freestyle Job
2. Add This App https://github.com/BenShelton/nuxt-example.git'
3. Add build step to test `npm install`
4. Run pipeline, it takes 24Sec
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/46735686/210042680-cbef939f-cdc9-48f9-acfc-3f85e766fa24.png">

With job cacher plugin
1. Create Freestyle Job
2. Add This App https://github.com/BenShelton/nuxt-example.git'
3. Add build step to test `npm install`
4. Using Job cacher 
<img width="966" alt="image" src="https://user-images.githubusercontent.com/46735686/210042261-87cf624d-7ba2-4a70-95ec-4f48411f90db.png">
7. Add build step to test `npm install`
8. Run first pipeline, it takes 49Sec (longer than without cacher)
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/46735686/210042998-ccdd8a21-d581-42d3-8ae5-71057ab21713.png">
9. Run Second pipeline, it takes 33Secs
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/46735686/210043095-2e67782d-8314-4209-a2f9-84aebd55fa26.png">

### Expected Results

The build time should be faster than without job cacher

### Actual Results

The build time is slower than without job cacher

**Comment by repolevedavaj** [comment]
@ariretiarno can you add the build log containing the time needed to cache/restore the directory?

**Comment by darxriggs** [comment]
@ariretiarno Can you provide the build log and the details about the configured storage backend?
