### ISSUE TITLE
Missing documentation on any dependent plugins

### ISSUE THREAD

**Issue by admmasters** [jenkinsci/jobcacher-plugin#147]
### Describe your use-case which is not covered by existing documentation.

I was alerted by another engineer that there were issues they were encountering that ended up being traced back to this plugin.

Seems like JobCacher requires the installation of some dependent plugins, but I can't see this anywhere in the docs, be great if we added some information on any dependent plugins that need installing as pre-requisites to using this. Currently not using S3 or Amazon credentials FWIW.

```
Processing DSL script jobs/addDependabotAndWorkflows.groovy
FATAL: com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentials
java.lang.ClassNotFoundException: com.cloudbees.jenkins.plugins.awscredentials.AmazonWebServicesCredentials
	at hudson.ClassicPluginStrategy$DependencyClassLoader.findClass(ClassicPluginStrategy.java:668)
```

An alternative solution could be only importing this plugin if using Amazon storage? (I'm not a plugin author and am using Jenkins in a work context so not sure if this is possible.)

**Comment by repolevedavaj** [comment]
@admmasters yes its true that this information is currently missing in the documentation. If you are not using S3 as storage, the plugin should not require the depending plugins, so its strange that this is happening for you. I will check if we are having anywhere a dependency to S3 which is not declared properly.

**Comment by darxriggs** [comment]
Declared dependencies in `pom.xml` are listed on https://plugins.jenkins.io/jobcacher/#dependencies.

**Comment by repolevedavaj** [comment]
I will close this as fixed for now (it has a link to the relevant section in the code in the readme). 
The dependencies should only be required while using S3. Feel free to reopen in case you run into this issue again.
