### ISSUE TITLE
Add option to disable cache creation

### ISSUE THREAD

**Issue by swain** [jenkinsci/jobcacher-plugin#150]
### What feature do you want to see added?

It would be great if an additional flag could be supported to allow _disabling_ cache creation in certain scenarios.

In particular: I'd like to be able to _only_ create new cache entries from the default branch, and _not_ create cache entries from e.g. PR builds.

It seems like an additional flag could be a simple solution to this -- something like `disableCacheCreation`:

```groovy
cache(
  defaultBranch: 'main',
  caches: [
    arbitraryFileCache(path: 'node_modules', cacheValidityDecidingFile: 'yarn.lock')
  ],
  disableCacheCreation: env.BRANCH_NAME != 'main' // <-- NEW
) {
  // ... 
}
```

The `maxCacheSize` option is probably the closest thing to an existing solution for this problem. But, I don't always know the size of the data I want to cache -- I really just want it to be cached _once_.

I'd be happy to implement this change if a maintainer could point me in the right direction for code changes.

**Comment by anderius** [comment]
This would be useful for my organization as well. We have a pipeline scripts that is used on 20-30 Jenkins instances, some with short lived agents, some with static agents that does not need cache.

Using this switch, I could save a lot of code like this:

```
if (utilities.enableCache()) {
          cache(maxCacheSize: XXXX, defaultBranch: 'main', caches: [
                  ...
          ]) {
            do some work...
          }
        } else {
           do the same work...
        }
```
