### ISSUE TITLE
Manually clear cache

### ISSUE THREAD

**Issue by MarcusElevait** [jenkinsci/jobcacher-plugin#235]
### What feature do you want to see added?

I want to have the ability to manually clear the cache.

**Comment by repolevedavaj** [comment]
You mean e.g. through the Jenkins UI?

**Comment by MarcusElevait** [comment]
Yes, like a button or something. Maybe it can be in that view, where we now can see the caches.

**Comment by repolevedavaj** [comment]
@MarcusElevait there is actually a feature exactly doing that but its broken if you compress your caches (what probably the majority of the users of this plugin do).
When I realized that, I checked whether it would be easy to fix it for all kinds of caches (including all implementations of item storages, like S3), but it seems not that easy..
A more easy option than implementing this in the UI could be a special parameter, similar to `skipSave`, e.g. `skipRestore`. That would allow you to add a special job parameter for doing that.
What do you think?

**Comment by MarcusElevait** [comment]
So what we're currently doing is, that we either set the `maxCacheSize` to `1` or we temporarily change the file defined in `cacheValidityDecidingFile` to invalidate the cache.
A special parameter for this would help people, who are not aware of such workarounds i guess. For us it would not be a benefit.
The downside of the parameter (and also of our current workaround) is, that you'd need to 

1. set this parameter in the Jenkinsfile
2. push to git
3. run the pipeline
4. remove the parameter
5. push to git
6. run the pipeline

**Comment by MarcusElevait** [comment]
Yes, this would be a workaround. I just think having a button to easily remove the caches without running a pipeline could be really comfortable :-)

**Comment by enyineer** [comment]
Thanks for your efforts @repolevedavaj!
