### ISSUE TITLE
S3 Bucket name cannot include a path

### ISSUE THREAD

**Issue by mattfirtion** [jenkinsci/jobcacher-plugin#256]
### Jenkins and plugins versions report

Version: 420.v16ee76f29824

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Configure Item Storage to use S3.  When setting the bucket name use a path to a directory within the bucket, i.e. `my-bucket/my-caches`.

AWS returns a 403

### Expected Results

Plugin should accept a directory within a bucket.  This previously worked in 378.v5e7c64638d63.

### Actual Results

After upgrading, the plugin no longer functioned as it did prior to upgrade and needed a config change.

**Comment by jonesbusy** [comment]
Created https://github.com/jenkinsci/jobcacher-plugin/issues/262 for last improvement

**Comment by jonesbusy** [comment]
Submited an improvement on https://github.com/jenkinsci/jobcacher-plugin/pull/263
