### ISSUE TITLE
Improve logging when using cacheValidityDecidingFile(s)

### ISSUE THREAD

**Issue by viceice** [jenkinsci/jobcacher-plugin#279]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.440.1
OS: Linux - 5.15.0-1053-azure
Java: 17.0.10 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:4.21.0
additional-identities-plugin:30.ve898b_a_9b_f104
analysis-model-api:12.1.0
ansicolor:1.0.4
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.3.1-1.0
asm-api:9.6-3.v2e1fa_b_338cd7
authentication-tokens:1.53.v1c90fd9191a_b_
authorize-project:1.7.1
aws-credentials:218.v1b_e9466ec5da_
aws-java-sdk-ec2:1.12.671-439.veec746c91fcb_
aws-java-sdk-minimal:1.12.671-439.veec746c91fcb_
basic-branch-build-strategies:81.v05e333931c7d
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1152.v6f101e97dd77
build-token-root:151.va_e52fe3215fc
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.901.vb_4c7a_da_75da_3
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
config-file-provider:968.ve1ca_eb_913f8c
coverage:1.13.0
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:657.v2b_19db_7d6e6d
data-tables-api:2.0.2-1
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-java-api:3.3.4-86.v39b_a_5ede342c
docker-plugin:1.6
docker-workflow:572.v950f58993843
durable-task:550.v0930093c4b_a_6
echarts-api:5.5.0-1
email-ext:2.105
embeddable-build-status:467.v4a_954796e45d
external-monitor-job:215.v2e88e894db_f8
font-awesome-api:6.5.1-3
forensics-api:2.4.0
git:5.2.1
git-client:4.7.0
git-forensics:2.1.0
git-parameter:0.9.19
gitea:1.4.7
gitea-checks:449.v0672c320ee47
github:1.38.0
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1781.va_153cda_09d1b_
google-oauth-plugin:1.330.vf5e86021cb_ec
gravatar:2.2
gson-api:2.10.1-15.v0d99f670e0a_7
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.33
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.16.2-378.v7e79818f53ce
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jjwt-api:0.11.5-77.v646c772fddb_0
jobcacher:449.v00180ef283de
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery3-api:3.7.1-2
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-52.v57de85cc4722
junit:1259.v65ffcef24a_88
kubernetes:4199.va_1647c280eb_2
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:0.11
ldap:711.vb_d1a_491714dc
lockable-resources:1243.v346d600eea_24
mailer:472.vf7c289a_4b_420
matrix-auth:3.2.2
matrix-project:822.824.v14451b_c0fd42
metrics:4.2.21-449.v6960d7c54c69
mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
nunit:485.ve8a_85357320d
oauth-credentials:0.646.v02b_66dc03d2e
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-graph-view:232.vc7ca_8d934725
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:491.vb_07d21da_1a_fb_
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2184.v0b_358b_953e69
pipeline-model-definition:2.2184.v0b_358b_953e69
pipeline-model-extensions:2.2184.v0b_358b_953e69
pipeline-multibranch-defaults:2.1
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2184.v0b_358b_953e69
pipeline-utility-steps:2.16.2
plain-credentials:179.vc5cb_98f6db_38
plugin-util-api:4.1.0
prism-api:1.29.0-13
saml:4.464.vea_cb_75d7f5e0
scm-api:689.v237b_6d3a_ef7f
scoring-load-balancer:76.v8e0a_59f13555
script-security:1326.vdb_c154de8669
sidebar-link:2.4.1
simple-theme-plugin:176.v39740c03a_a_f5
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-agent:346.vda_a_c4f2c8e50
ssh-credentials:322.v124df57ed808
ssh-slaves:2.948.vb_8050d697fec
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.142.v748523a_76693
variant:60.v7290fc0eb_b_cd
versioncolumn:243.vda_c20eea_a_8a_f
warnings-ng:11.2.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1291.v51fd2a_625da_7
workflow-basic-steps:1049.v257a_e6b_30fb_d
workflow-cps:3883.vb_3ff2a_e3eea_f
workflow-durable-task-step:1331.vc8c2fed35334
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:865.v43e78cc44e0d

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Both linux

### Reproduction steps

```groovy
 cache(skipSave: env.BRANCH_NAME != 'main', defaultBranch: 'main', caches: [arbitraryFileCache(
      path: '.cache/nuget',
      cacheValidityDecidingFile: '**/packages.lock.json',
      compressionMethod: 'TAR_ZSTD',
      cacheName: 'dotnet'
    )]) {
    sh 'dotnet restore --locked-mode sx.sln'
  }
```

### Expected Results

It should restore the cache from main

### Actual Results

It shows cache outdated

```
[2024-03-19T08:48:23.444Z] [Pipeline] cache
[2024-03-19T08:48:23.445Z] [Cache for .cache/nuget (dotnet) with id 19344a3f2f41b742d864cb4dc43ad0cf] Searching cache in job specific caches...
[2024-03-19T08:48:23.497Z] [Cache for .cache/nuget (dotnet) with id 19344a3f2f41b742d864cb4dc43ad0cf] Searching cache in default caches...
[2024-03-19T08:48:24.136Z] [Cache for .cache/nuget (dotnet) with id 19344a3f2f41b742d864cb4dc43ad0cf] cacheValidityDecidingFile configured, but previous hash does not match - cache outdated
[2024-03-19T08:48:24.136Z] [Cache for .cache/nuget (dotnet) with id 19344a3f2f41b742d864cb4dc43ad0cf] Skip restoring cache as no up-to-date cache exists
```

that cache exists in s3

![image](https://github.com/jenkinsci/jobcacher-plugin/assets/1798109/263148b6-1366-48d6-b2fa-7ee2c48b8a28)

**Comment by viceice** [comment]
that branch is one commit ahead of main and only changes `package.json` and `pnpm-lock.yaml`, so hashes for `**/packages.lock.json` should match.

there is always a `git reset --hard` and `git clean -ffdx` before restore

**Comment by viceice** [comment]
@jonesbusy @repolevedavaj Any chance to look into this? this causes a lot extra network trafic and slow restores

**Comment by jonesbusy** [comment]
Hi,

For the moment I don't have bandwidth to take a look at the bugs and enhancement of this plugin.

I'm just co-maintainer of it because I built recently some extension for Artifactory storage. I'm also planning to use more and more jobcacher at scale, but until then I will not put any effort to implement nor fix anything I'm not facing.

But I'm more than happy to review/merge any PR. Contributions are welcome.

Thanks

**Comment by repolevedavaj** [comment]
@viceice sorry for the late response. I actually tried to reproduce this, but in my builds the `cacheValidityDecidingFile` works fine. Maybe it is related with the glob pattern. Do you know how many files match the `**/packages.lock.json` glob?

**Comment by remilibon** [comment]
hello,

we had the same issue and we think it is related to the glob pattern usage.

Code:
```
 caches: [arbitraryFileCache(path: cachePath,
                            cacheName: config.cacheName,
                            cacheValidityDecidingFile: ".mvn,**/pom.xml")]) {
```

Logs - on the first and second run
```
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Searching cache in job specific caches...
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Searching cache in default caches...
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Skip restoring cache as no up-to-date cache exists
```

We tested the hypothesis it is caused by the glob pattern usage and tried to list explicitly the files and providing them to the plugin.
You can see the "fix" with the usage of findFiles.

Code:
```
 caches: [arbitraryFileCache(path: cachePath,
                            cacheName: config.cacheName,
                            cacheValidityDecidingFile: findFiles(glob: '.mvn,**/pom.xml').join(',') )]) {
```

Logs - first run 
```
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Searching cache in job specific caches...
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Searching cache in default caches...
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Skip restoring cache as no up-to-date cache exists
```

Logs - second run

```
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Searching cache in job specific caches...
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Found cache in job specific caches
[Cache for .repository with id 55cd1b309d2c1e8d76b017c0f5319d96] Restoring cache...
```

Hope this help

**Comment by viceice** [comment]
interesting, will investigate further

**Comment by repolevedavaj** [comment]
@viceice I created a branch (https://github.com/jenkinsci/jobcacher-plugin/pull/290) containing a change to log the resolved files and hash. Are you able to install plugins manually on your Jenkins? If yes, you could use this state to check whether the files/hash are the same while saving/restoring.

According to the code which resolves the files using a glob, the files are returned sorted, so I don't expect that this is the issue.

**Comment by viceice** [comment]
sure, will try in a few minutes

**Comment by viceice** [comment]
Ok, found something interesting.

1. my global agent is a linux agent
2. i run a build stage inside a container and restore. there to get hash a
3. i run a test stage inside another container and restore a second time. there i got a hash b

this only happens when using multiple files, the container image is always the same.

and the issue is this file: `net8.0/linux-x64/packages.lock.json` which is a build file, so i need to exclude it.

So the hash is flip flopping 🙈 

Thanks for the additional logging, i would never identify the error without those logs

**Comment by viceice** [comment]
Could there be an issue if the `defaultBranch` value contains a slash? 
eg: `defaultBranch: 'release/v2'`

**Comment by viceice** [comment]
Yes, here the slash is encoded:
https://github.com/jenkinsci/jobcacher-plugin/blob/bedb79fc57e2670569dbe368f2cd95f16980a62b/src/main/java/jenkins/plugins/itemstorage/s3/S3ItemStorage.java#L92

and here not:
https://github.com/jenkinsci/jobcacher-plugin/blob/bedb79fc57e2670569dbe368f2cd95f16980a62b/src/main/java/jenkins/plugins/itemstorage/s3/S3ItemStorage.java#L97

![image](https://github.com/jenkinsci/jobcacher-plugin/assets/1798109/f077da1a-3826-4a81-add2-f98b5fba0c43)

**Comment by repolevedavaj** [comment]
> Yes, here the slash is encoded:
> 
> https://github.com/jenkinsci/jobcacher-plugin/blob/bedb79fc57e2670569dbe368f2cd95f16980a62b/src/main/java/jenkins/plugins/itemstorage/s3/S3ItemStorage.java#L92
> 
> and here not:
> 
> https://github.com/jenkinsci/jobcacher-plugin/blob/bedb79fc57e2670569dbe368f2cd95f16980a62b/src/main/java/jenkins/plugins/itemstorage/s3/S3ItemStorage.java#L97
> 
> ![image](https://private-user-images.githubusercontent.com/1798109/323227972-f077da1a-3826-4a81-add2-f98b5fba0c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzkwOTMsIm5iZiI6MTcxMzM3ODc5MywicGF0aCI6Ii8xNzk4MTA5LzMyMzIyNzk3Mi1mMDc3ZGExYS0zODI2LTRhODEtYWRkMi1mOThiNWZiYTBjNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMTgzMzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmNjNjEyMjhjODFjZmVkZWVkMDk2NjRlMjRhNjJiYWVkZGM2MzY4MDg0NzBjNGQwMzEyN2U0M2ZhOWMzNWRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GsdOKkfprfIb560THUWPSw03s3L70nf6C9XjsxQ_hPk)

See #291
