### ISSUE TITLE
URL encode default branch name

### ISSUE THREAD

**Issue by repolevedavaj** [jenkinsci/jobcacher-plugin#291]
Yes, here the slash is encoded:
https://github.com/jenkinsci/jobcacher-plugin/blob/bedb79fc57e2670569dbe368f2cd95f16980a62b/src/main/java/jenkins/plugins/itemstorage/s3/S3ItemStorage.java#L92

and here not:
https://github.com/jenkinsci/jobcacher-plugin/blob/bedb79fc57e2670569dbe368f2cd95f16980a62b/src/main/java/jenkins/plugins/itemstorage/s3/S3ItemStorage.java#L97

![image](https://github.com/jenkinsci/jobcacher-plugin/assets/1798109/f077da1a-3826-4a81-add2-f98b5fba0c43)

_Originally posted by @viceice in https://github.com/jenkinsci/jobcacher-plugin/issues/279#issuecomment-2061216689_

**Comment by repolevedavaj** [comment]
@viceice can you check whether this change solves your issue? I seems Jenkins is URL encoding branch names, so we do now the same.

**Comment by viceice** [comment]
testing it now

**Comment by viceice** [comment]
works 💪  Thanks 🤗
