### ISSUE TITLE
AWS S3 Cache not working

### ISSUE THREAD

**Issue by paul-uz** [jenkinsci/jobcacher-plugin#360]
### Jenkins and plugins versions report

I have installed the plugin and configured the AWS S3 setup in Jenkins config

![Image](https://github.com/user-attachments/assets/585b27ff-cfa6-4547-bb59-73f999e1db0b)

Next I tried adding Job Cacher to a Job, via the Job Config. I can see the option in Build Environment

![Image](https://github.com/user-attachments/assets/61acb90f-9db1-4aab-b7d7-1f5cbad80db6)

So now the logical reasoning is I need to add a cache, but I don't see anything for S3

![Image](https://github.com/user-attachments/assets/9c658f9d-c9b5-4743-8547-99437bab971f)

For me, this is a bug.

### What Operating System are you using (both controller, and any agents involved in the problem)?

EC2 on Amazon Linux 2023

### Reproduction steps

1. Install plugin
2. Configure in Jenkins config
3. Edit Job
4. Enabled Job Cacher

### Expected Results

I expect to see an option for S3 in the dropdown when clicking "Add Cache" in a Job

### Actual Results

No entry for S3

### Anything else?

Documentation states S3 support as a feature, just there are no examples on how to set it up and get it working. The plugin dependencies are mentioned by way of a link to some code and that's it. I have the correct plugins installed and enabled.

**Comment by repolevedavaj** [comment]
The caches configured on the job are automatically stored on the globally configured cache storage. Hope that helps.

**Comment by paul-uz** [comment]
For anyone else having issues with this plugin, here is the answer:

* Install Plugin
* Configure Item Storage in System
  * This sets the global storage type for all jobs that use Job Cacher
* Create a new job, or edit a job and add Job Cacher in Build Environment
  * You will _not_ see any option for S3 or the likes, just Arbitrary File Cache. This is correct
* Add a Cache - Arbitrary File Cache and configure it
* Save the job settings

The job will run and as part of the environment setup, it will look for caches on your selected Item Storage (S3 in this case) and if it finds a match, it will download and restore the files. At the end of the job, the files selected for caching will be cached and uploaded to S3.
