### ISSUE TITLE
Support wildcard for `cacheValidityDecidingFile`

### ISSUE THREAD

**Issue by viceice** [jenkinsci/jobcacher-plugin#69]
### What feature do you want to see added?

I need this for dotnet projects with lockfiles, every project has it's own `packages.lock.json`

**Comment by repolevedavaj** [comment]
Can you give me an example and how the configuration should look like in this case?

**Comment by viceice** [comment]
maybe `**/packages.lock.json`. so some kind of a `glob`

**Comment by repolevedavaj** [comment]
We had a similar issue in the company I work for. As we are using scripted pipelines here, we could easily collect the paths by using something like `findFiles('**/package-lock.json')`. What I could imagine is that we introduce an additional component, which allows to create a cache for all locations matching the glob, but I still need to check it in more detail.

**Comment by repolevedavaj** [comment]
@viceice are you configuring your caches in the pipeline or as build wrapper?

**Comment by viceice** [comment]
in the pipeline options

**Comment by viceice** [comment]
like in #70

**Comment by repolevedavaj** [comment]
OK now I got it. So the `CacheStep` is used (https://www.jenkins.io/doc/book/pipeline/syntax/#stage-options). I am still confused about this declarative syntax..

**Comment by viceice** [comment]
no, as `**/packages.lock.json` comes from dotnet. there every project has it's own lockfile. so i need multiple files for cache validity computation

**Comment by repolevedavaj** [comment]
@viceice I created a PR with this change. Let me know if it works for you :)

**Comment by viceice** [comment]
will try tomorrow (hopefully 🙃)

**Comment by viceice** [comment]
seems to work 🎉
