### ISSUE TITLE
Configurable cache directory for LocalItemStorage

### ISSUE THREAD

**Issue by anderius** [jenkinsci/jobcacher-plugin#83]
### What feature do you want to see added?

It would be useful if it was possible to configure the directory used for local item storage cache, to have the possiblity of placing it outside the job folder.

The reason for this is to better separate and control disk usage, and the possibility to have the data on two different mounted volumes.

**Comment by repolevedavaj** [comment]
Yes, that sounds like a good extension. The cool thing about storing the cache at the same location as the job is that the deletion of a job is deleting the relevant caches too. That's probably something which should work with this kind of storage too, right?

**Comment by repolevedavaj** [comment]
I created a first draft of your proposal: #86
It would be great if you could validate if it fulfills your needs. You can test it by using the incrementals build: https://ci.jenkins.io/job/Plugins/job/jobcacher-plugin/job/PR-86/

**Comment by anderius** [comment]
Cool, I will have a look!

Deletion of the cache when the job is deleted would be nice, but a max time-to-live would also work for us.

My company has a lot of teams with Jenkins running in k8s, without resizable persistent volumes. That is why the ability to mount a cache directory someplace else is very useful.

**Comment by anderius** [comment]
@repolevedavaj I have tested this, and it works perfectly! The cache is located in the specified folder, and is cleared when the job is deleted. This is excellent!

**Comment by repolevedavaj** [comment]
Sounds great. I just added some additional tests and will release it asap.

**Comment by repolevedavaj** [comment]
voilà: https://github.com/jenkinsci/jobcacher-plugin/releases/tag/281.v338c5559864d
