### ISSUE TITLE
Is this plug-in good for concurrent build

### ISSUE THREAD

**Issue by walcomel199** [jenkinsci/jobcacher-plugin#85]
### Describe your use-case which is not covered by existing documentation.

docker swarm plug-in have same function,but concurrent build Support is not friendly
The project write back cache has been built, which will affect subsequent construction

Machine translation may be inaccurate -- I am not very good at English

**Comment by repolevedavaj** [comment]
I think it should work even for concurrent builds as the cache will be locked before creating it. Let me know if you have any issues using it in concurrent scenarios.

**Comment by walcomel199** [comment]
thank you ！You got a follower +1
