### ISSUE TITLE
Support zstd compression

### ISSUE THREAD

**Issue by viceice** [jenkinsci/jobcacher-plugin#91]
### What feature do you want to see added?

Support zstd compression because it's much faster and better than zip and gzip.

i think `Apache Commons Compress`[^1] can be used for it.

[^1]: https://commons.apache.org/proper/commons-compress/

**Comment by repolevedavaj** [comment]
Sounds really interesting - I will take a look!

**Comment by repolevedavaj** [comment]
@viceice I did a first implementation. Feel free to try it out: https://ci.jenkins.io/job/Plugins/job/jobcacher-plugin/job/PR-97/
I am currently just using the default settings for zstd and do not allow to configure it (e.g. compression level).

**Comment by viceice** [comment]
nice, will try it out the next days
