### ISSUE TITLE
Support Multiple use in pipeline

### ISSUE THREAD

**Issue by lcc3108** [jenkinsci/jobcacher-plugin#92]
### What feature do you want to see added?

Overwrite cache multiple calls on one pipeline.
I wish I could cache with jobnNme + customName as an additional feature.

ex)                cache(maxCacheSize: 1000, defaultBranch: 'develop', caches: [[$class: 'ArbitraryFileCache', path:  cacheValidityDecidingFile: 'build.gradle', compressionMethod: 'TARGZ',excludes: '**/*.lock'], customName: auth-server]) {

**Comment by repolevedavaj** [comment]
Yes, sounds like a valid use-case for me.
