### ISSUE TITLE
Help needed for caching Android builds

### ISSUE THREAD

**Issue by gianpaolof** [jenkinsci/jobcacher-plugin#94]
hello
I have a multibranch pipeline job for Android and I use docker slaves.
Is it possible to have an example of a proper configuration so that gradle libraries are cached and not downloaded at every build? I'm trying with this one:

       cache(maxCacheSize: 10000, defaultBranch: 'develop', caches: [[$class: 'ArbitraryFileCache', path: 'node_modules', cacheValidityDecidingFile: 'build.gradle', compressionMethod: 'TARGZ',excludes: '**/*.lock']])

but I always see in the logs:

      [Cache for node_modules] Skip restoring cache as no up-to-date cache exists

Do I have to create a folder called "node_modules" in the root dir of the controller?

thanks

**Comment by gianpaolof** [comment]
I have tried with this

       cache(maxCacheSize: 10000, defaultBranch: 'develop', caches: [[$class: 'ArbitraryFileCache', cacheValidityDecidingFile: 'build.gradle', compressionMethod: 'TARGZ',excludes: '**/*.lock']])

but I get a Null pointer:
java.lang.NullPointerException
	at hudson.FilePath.isAbsolute(FilePath.java:296)
	at hudson.FilePath.resolvePathIfRelative(FilePath.java:281)
	at hudson.FilePath.<init>(FilePath.java:272)
	at hudson.FilePath.child(FilePath.java:1514)
	at jenkins.plugins.jobcacher.ArbitraryFileCache.resolvePath(ArbitraryFileCache.java:169)

**Comment by repolevedavaj** [comment]
Is `node_modules` really correct cache location for an Gradle Android build? I would expect that you should cache `$USER_HOME/.gradle/caches` or `~/.gradle/caches`. `node_modules` is something NodeJS specific.

**Comment by gianpaolof** [comment]
oh shame on me. i thought that was the path where the cache should have been created. apologies and thanks.
